---
- name: Run Database container
  hosts: databases
  become: yes

  tasks:
    - name: Copy database init files
      copy:
        src: initDB.sql
        dest: /home/azureuser

    - name: Deploy Database container
      community.docker.docker_container:
        name: postgres-petclinic
        image: postgres:9.6.0
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: "petclinic"
          POSTGRES_PASSWORD: "petclinic"
        volumes:
          - /home/azureuser/:/docker-entrypoint-initdb.d/
        restart_policy: always

