---
- name: Configure Frontend
  hosts: frontends
  become: true
  gather_facts: no

  vars:
    backend_ip: "localhost"

  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/spring-petclinic/spring-petclinic-angular.git
        dest: /home/azureuser/spring-petclinic-angular

    - name: Login to Docker
      community.docker.docker_login:
        username: aszpej
        password: Paim2023_

    - name: Copy Dockerfile from host to target machine
      copy:
        src: /home/azureuser/Dockerfile
        dest: /home/azureuser/spring-petclinic-angular/Dockerfile

    - name: Build image
      shell: docker build --build-arg HOST_IP={{ backend_ip }} -t petclinic-frontend .
      args:
        chdir: /home/azureuser/spring-petclinic-angular
    
    - name: Run Frontend container
      community.docker.docker_container:
        name: frontend
        image: petclinic-frontend
        ports: "8080:80"
        restart_policy: always
      